### ISSUE TITLE
Question about Next K Token Prediction

### ISSUE THREAD

**Issue by tianweiy** [fusiming3/MARS#2]
Congrats on the great work! The paper is really really impressive. 

One question that I am wondering is the exact implementation of the next K token prediction. If I understand correctly, for the 256x256->1024x1024 task, the model will predict a 4x4 patch iteratively following the same raster scan order? 

Is this correct? Thank you for the clarifications!

**Comment by Robootx** [comment]
No, we use mask token prediction as training task. During prediction, we predict all the image tokens and sample k tokens at each auto-regressive step, the order is random

**Comment by tianweiy** [comment]
I see. Thank you very much!
